In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [7]:
digits = np.arange(1, 21)
ones = np.ones(20, )
result = pow((2 * ones), digits) / digits
result

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [8]:
n = 5
iMult3 = 3 * np.arange(1, n + 1)
iMult4 = 4 * np.arange(1, n + 1)

ones01 = 0.1 * np.ones(n,)
ones02 = 0.2 * np.ones(n, )

np.sum(pow(ones01, iMult3) * pow(ones02, iMult4))

1.6000025600040968e-06

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [17]:
matrix = np.zeros((8, 8))
evenNumbers = np.arange(0, 8, 2)
oddNumbers = np.arange(1, 8, 2)

matrix[evenNumbers, :] = np.arange(0, 8) % 2
matrix[oddNumbers, :] = np.arange(1, 9) % 2

matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [18]:
X = np.random.random((5, 2))

r = np.sum(X ** 2, axis=1) ** 0.5
X[:,0] = r
X[:,1] = np.arcsin(X[:,1]/r)
X

array([[1.04613462, 1.14832021],
       [0.48123924, 1.13885058],
       [0.18011971, 0.22248351],
       [0.9407425 , 1.45506518],
       [0.8487878 , 1.09441938]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [33]:
X = np.random.random((10, 10))

argmax = X.flat[np.argmax(X)]
x, y = np.where(X ==argmax)
X, list(zip(x,y))

(array([[0.38877072, 0.03028416, 0.9304599 , 0.11755927, 0.02023043,
         0.99859012, 0.12836967, 0.10820308, 0.70053978, 0.1140179 ],
        [0.77936289, 0.21499804, 0.01783848, 0.67966097, 0.83471229,
         0.90001463, 0.56985646, 0.72246946, 0.56822157, 0.60135734],
        [0.9465999 , 0.45886615, 0.07487376, 0.75187439, 0.794679  ,
         0.99063516, 0.9328675 , 0.41241349, 0.93768013, 0.06365187],
        [0.01713255, 0.60175404, 0.74638189, 0.65434158, 0.63504828,
         0.6834018 , 0.99066818, 0.68593497, 0.35989316, 0.32091026],
        [0.50254631, 0.63865669, 0.65875845, 0.94170877, 0.70603006,
         0.27753401, 0.52207798, 0.36137922, 0.97218384, 0.92567656],
        [0.05498202, 0.75839482, 0.45037849, 0.13296115, 0.9504513 ,
         0.50892618, 0.45001976, 0.21892734, 0.95991082, 0.23931252],
        [0.95011738, 0.76198357, 0.27583541, 0.12533382, 0.89676888,
         0.38149326, 0.7195719 , 0.655991  , 0.85192251, 0.25324301],
        [0.84767582, 0.1584

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [38]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
distances = np.sum((X - y) ** 2, axis=1)
X, y, X[np.argmin(distances), :]

(array([[0.35484398, 0.5827947 ],
        [0.53302174, 0.60740255],
        [0.90092389, 0.17592125],
        [0.7691334 , 0.9002715 ],
        [0.99345889, 0.28167333],
        [0.11668877, 0.61368859],
        [0.40287853, 0.07982821],
        [0.92713297, 0.65051074],
        [0.73876165, 0.6052482 ],
        [0.00211516, 0.80294226]]),
 array([[0.32345403, 0.44433731]]),
 array([0.35484398, 0.5827947 ]))

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
def f(x):
    if x < 0:
        return x ** 2 + 2*x + 6
    if 0 <= x <= 2:
        return x  + 6
    if x >= 2:
        return x ** 2 + 4*x-4

x = np.linspace(-3, 3, 100)

list(map(f, x))

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [47]:
X = np.random.random((10, 10))

(X.T - X.mean(axis=1)).T, (X.T - X.mean(axis=1)).T.mean(axis=1)

array([1.5, 2.5])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
X.mean(), X.var()

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [51]:
x = np.arange(5)
x = (x+x.reshape(5, 1))
x = x % 5
x

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [55]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[4, 0, 4, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [56]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    values = s * np.random.random(c)
    res = np.argmin((np.cumsum(x) <= values.reshape(-1, 1)), axis=1)
    return res

            
sample([50, 3, 1, 7, 20], 5)

array([0, 0, 0, 0, 0])